"""make_catalog.py - courses/*/course.json + cartridges/*.json sidecars -> catalog.json + .github/CODEOWNERS

catalog.json is a LIGHT index: one row per course, one row per kit, with status,
file, size, version and counts. The heavy per-kit detail the widget needs to patch
dates, points, groups and published state (modules, groups, graded_items, settings)
stays in cartridges/<kit>.json, and the index names it as `sidecar`. With 130+
courses the index stays well under 200 KB; embedding sidecars would push it past
10 MB and slow every teacher's first load.

usage: make_catalog.py [--check]     (--check: write nothing, exit 1 if the files on disk are stale)
"""
import datetime
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import kitlib as L  # noqa: E402

LIGHT_FIELDS = ('label', 'file', 'bytes', 'version', 'built', 'items', 'counts', 'weighted',
                'source', 'front_page', 'spec_sha', 'status')

NOTE = ('Generated by _build/make_catalog.py from courses/*/course.json and cartridges/*.json. '
        'Do not hand-edit. A kit is "ready" when its cartridge and sidecar exist; the widget '
        'fetches the sidecar named in `sidecar` when a teacher selects the kit.')


def build():
    sidecars = {}
    for p in glob.glob(os.path.join(L.CARTRIDGES, '*.json')):
        s = L.read_json(p)
        sidecars[s['id']] = s
    courses, used, problems = [], set(), []
    seen_codes = set()
    for d, c in L.load_courses():
        folder = os.path.basename(d)
        code = str(c.get('code', ''))
        if code != folder:
            problems.append('courses/%s: code %r must equal the folder name' % (folder, code))
        if code in seen_codes:
            problems.append('duplicate course code %s' % code)
        seen_codes.add(code)
        for k in ('title', 'grade', 'subject'):
            if not c.get(k):
                problems.append('courses/%s/course.json: missing %r' % (folder, k))
        row = {'code': code, 'title': c.get('title'), 'grade': str(c.get('grade', '')), 'subject': c.get('subject'),
               'owner': c.get('owner', ''), 'kits': []}
        if c.get('canvas_title'):
            row['canvas_title'] = c['canvas_title']
        # Optional: `level` (Honors, Standard, ...) and `family` (the shared title two
        # levels have in common) group sibling courses in the widget's finder. When
        # absent the widget reads the level out of the title.
        for f in ('level', 'family'):
            if c.get(f):
                row[f] = str(c[f])
        for kit in c.get('kits', []):
            kid = kit.get('id', '')
            if not kid.startswith(code + '-') or not L.KIT_ID.match(kid):
                problems.append('courses/%s: kit id %r must be %s-<s1|s2|q1..q4|t1..t3|full>[-live|-od]' % (folder, kid, code))
            if not kit.get('label'):
                problems.append('courses/%s: kit %s has no label' % (folder, kid))
            entry = {'id': kid, 'label': kit.get('label')}
            # Optional section type: `mode` in course.json, or the -live / -od id suffix.
            m = L.KIT_ID.match(kid)
            mode = str(kit.get('mode') or (m.group('mode') if m else '') or '').lower()
            if mode and mode not in L.MODES:
                problems.append('courses/%s: kit %s mode %r must be live or od' % (folder, kid, mode))
            if mode and m and m.group('mode') and m.group('mode') != mode:
                problems.append('courses/%s: kit %s id says %s but mode says %s' % (folder, kid, m.group('mode'), mode))
            if mode:
                entry['mode'] = mode
            if kit.get('canvas_course_id') is not None:
                entry['canvas_course_id'] = kit['canvas_course_id']
            s = sidecars.get(kid)
            if s:
                used.add(kid)
                for f in LIGHT_FIELDS:
                    if f in s:
                        entry[f] = s[f]
                entry['sidecar'] = 'cartridges/%s.json' % kid
                entry['student_modules'] = sum(1 for m in s.get('modules', []) if m.get('published', True))
                entry['warnings'] = len((s.get('verify') or {}).get('warnings') or [])
                if not row.get('canvas_title'):
                    row['canvas_title'] = s.get('title')
            else:
                entry['status'] = 'pending'
                if os.path.exists(os.path.join(d, kid + '.spec.json')):
                    entry['status'] = 'spec-only'   # authored, not yet built: run _build/kit.py <kit>
            row['kits'].append(entry)
        courses.append(row)
    orphans = sorted(set(sidecars) - used)
    if orphans:
        problems.append('sidecars with no course.json kit entry: %s' % orphans)
    courses.sort(key=lambda r: (r['subject'] or '', r['grade'].zfill(2), r['code']))
    catalog = {'note': NOTE, 'generated': None, 'courses': courses}
    return catalog, problems


def codeowners(catalog):
    lines = ['# Generated by _build/make_catalog.py from courses/*/course.json "owner". Do not hand-edit.',
             '# The maintainer owns everything not claimed below.',
             '* @optimaondemand', '']
    for c in catalog['courses']:
        if c.get('owner'):
            lines.append('/courses/%s/ @%s' % (c['code'], c['owner'].lstrip('@')))
            for k in c['kits']:
                lines.append('/cartridges/%s.* @%s' % (k['id'], c['owner'].lstrip('@')))
    return '\n'.join(lines) + '\n'


def strip_generated(cat):
    return json.dumps({k: v for k, v in cat.items() if k != 'generated'}, sort_keys=True)


def main():
    check = '--check' in sys.argv
    catalog, problems = build()
    if problems:
        for p in problems:
            print('FAIL', p)
        sys.exit(1)
    owners = codeowners(catalog)
    cat_path = os.path.join(L.ROOT, 'catalog.json')
    own_path = os.path.join(L.ROOT, '.github', 'CODEOWNERS')
    if check:
        stale = []
        if not os.path.exists(cat_path) or strip_generated(L.read_json(cat_path)) != strip_generated(catalog):
            stale.append('catalog.json')
        if not os.path.exists(own_path) or open(own_path, encoding='utf-8').read() != owners:
            stale.append('.github/CODEOWNERS')
        if stale:
            print('FAIL stale: %s (run python _build/make_catalog.py)' % ', '.join(stale))
            sys.exit(1)
        print('catalog.json and CODEOWNERS are current')
        return
    catalog['generated'] = datetime.datetime.now().isoformat(timespec='seconds')
    L.write_json(cat_path, catalog)
    os.makedirs(os.path.dirname(own_path), exist_ok=True)
    with open(own_path, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(owners)
    kits = [k for c in catalog['courses'] for k in c['kits']]
    ready = [k['id'] for k in kits if k.get('status') == 'ready']
    print('catalog.json: %d courses, %d kits (%d ready, %d spec-only, %d pending), %s' % (
        len(catalog['courses']), len(kits), len(ready),
        sum(1 for k in kits if k.get('status') == 'spec-only'),
        sum(1 for k in kits if k.get('status') == 'pending'),
        L.human(os.path.getsize(cat_path))))
    if ready:
        print('ready:', ' '.join(ready))


if __name__ == '__main__':
    main()
